import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Providers from "@/components/Layouts/Providers";
import { Toaster } from "sonner";
import CreateTaskModal from '@components/Modals/CreateTask/CreateTask';
import EditObjectModal from '@components/Modals/EditObject/EditObject';
import EditTaskModal from '@components/Modals/EditTask/EditTask';
import DeleteObjectModal from '@components/Modals/DeleteObject/DeleteObject';
import DeleteTaskModal from '@components/Modals/DeleteTask/DeleteTask';
import CreateEmployeeModal from '@components/Modals/CreateEmployee/CreateEmployee';
import EditEmployeeModal from '@components/Modals/EditEmployee/EditEmployee';
import DeleteEmployeeModal from '@components/Modals/DeleteEmployee/DeleteEmployee';
import CreateToolModal from '@components/Modals/CreateTool/CreateTool';
import EditToolModal from '@components/Modals/EditTool/EditTool';
import DeleteToolModal from '@components/Modals/DeleteTool/DeleteTool';
import CreateObjectModal from "@/components/Modals/CreateObject/CreateObject";
import favicon from '../../public/favicon.ico'

import "@styles/vars.scss";
import '@styles/globals.scss';

const openSans = Open_Sans({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: {
    template: 'Nuegas | %s',
    default: 'Nuegas | Главная',
  },
  icons: favicon.src,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru">
      <body
        className={`${openSans.className} antialiased`}
      >
        <Providers>
        <Toaster richColors />
      <CreateObjectModal />
      <CreateTaskModal />
      <EditObjectModal />
      <EditTaskModal />
      <DeleteObjectModal />
      <DeleteTaskModal />
      <CreateEmployeeModal />
      <EditEmployeeModal />
      <DeleteEmployeeModal />
      <CreateToolModal />
      <EditToolModal />
      <DeleteToolModal />
          <div className="wrapper">
          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
